[package]
name = "cohort_4"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
# [executable]
[dependencies]

[cairo]
enable-gas = false

[dev-dependencies]
cairo_test = "2.11.2"
# cairo_execute = "2.11.3"
